load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "Hello",
    srcs = ["Hello.java"],
    deps = [
        "@maven//:io_vertx_vertx_core",
        "@maven//:io_vertx_vertx_web",
    ],
)